name: "Spoolman Server"
description: "Run the latest stable version of Spoolman."
url: "https://github.com/donkie/spoolman"
slug: "spoolman_server"
init: false
arch:
  - aarch64
  - amd64
  - armv7
devices:
  - "/dev/ttyUSB0"
  - "/dev/sda"
  - "/dev/sdb"
  - "/dev/sdc"
  - "/dev/sdd"
  - "/dev/sde"
  - "/dev/sdf"
  - "/dev/sdg"
  - "/dev/fuse"
  - "/dev/sda1"
  - "/dev/sdb1"
  - "/dev/sdc1"
  - "/dev/sdd1"
  - "/dev/sde1"
  - "/dev/sdf1"
  - "/dev/sdg1"
  - "/dev/sda2"
  - "/dev/sdb2"
  - "/dev/sdc2"
  - "/dev/sdd2"
  - "/dev/sde2"
  - "/dev/sdf2"
  - "/dev/sdg2"
  - "/dev/sda3"
  - "/dev/sdb3"
  - "/dev/sda4"
  - "/dev/sdb4"
  - "/dev/sda5"
  - "/dev/sda6"
  - "/dev/sda7"
  - "/dev/sda8"
startup: application
udev: true
webui: "[PROTO:option_name]://[HOST]:[PORT:8000]"
environment:
  SPOOLMAN_DIR_DATA: "/addon_configs/spoolman"
map:
  - config:rw  
boot: auto
ports:
  8000/tcp: 8000
image: ghcr.io/donkie/spoolman
version: 0.21
